# name: Node.js Package

# on:
#   release:
#     types: [published]
      

# jobs:
#   build-and-publish-npm:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           registry-url: https://registry.npmjs.org/
#           scope: abcdpackage
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Set SHAs
#         uses: nrwl/nx-set-shas@v4
#       - name: Install root dependencies
#         run: pnpm install
#       - name: Set affected libs
#         id: set-affected-libs
#         run: | 
#           echo "AFFECTED_LIBS=$(pnpm nx show projects --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --t=build --exclude=@abcdpackage/source | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
#       - name: Install dependencies and update package versions
#         shell: bash {0}
#         run: |
#           git checkout main
#           for lib in ${{ steps.set-affected-libs.outputs.AFFECTED_LIBS }}
#           do 
#             cd $lib
#             npm version patch
#             pnpm install
#             cd ../
#           done
#       - name: Lint and build all affected projects
#         run: | 
#           for i in {1..2}; do pnpm nx affected -t lint --fix --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --exclude=@abcdpackage/source; done
#           pnpm nx affected -t lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --exclude=@abcdpackage/source
#           pnpm nx affected -t build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --exclude=@abcdpackage/source
#       - name: Publish npm packages
#         run: | 
#           for lib in ${{ steps.set-affected-libs.outputs.AFFECTED_LIBS }}
#           do
#             cd dist/$lib
#             npm publish --access=public
#             cd ../../
#           done

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Set SHAs
        uses: nrwl/nx-set-shas@v4
      - name: Install root dependencies
        run: pnpm install
      - name: Set affected libs
        id: set-affected-libs
        run: |
          echo "AFFECTED_LIBS=$(pnpm nx show projects --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --t=build --exclude=@abcdpackage/source | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
      - name: Install dependencies and update package versions
        shell: bash {0}
        run: |
          for lib in ${{ steps.set-affected-libs.outputs.AFFECTED_LIBS }}
          do 
            cd $lib
            pnpm install
            cd ../
          done
      - name: Build and Publish affected projects
        run: |
          pnpm nx affected -t build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --exclude=@abcdpackage/source

