name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Build and publish
        uses: nrwl/nx-set-shas@v4
      - name: Install dependencies and update package versions
        shell: bash {0}
        run: |
          pnpm install
          echo $(pnpm nx show projects --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --t=build)
          for lib in $(pnpm nx show projects --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --t=build)
          do 
            cd $lib
            echo $lib
            npm version patch
            pnpm install
            cd ../
          done
      - name: push new version commits
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git status
          git commit -m "update affected package versions"
          git push origin main
      - run: pnpm nx affected -t lint --fix -t build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
